### ISSUE TITLE
`reset()` causing coroutine to break somehow

### ISSUE THREAD

**Issue by EkardNT** [bxparks/AceRoutine#20]
`reset()` either seems to be breaking coroutines its called on, or I am not understanding how it should be used.

I am building a device that needs to play short melodies, where a melody is a sequence of Arduino `tone()` calls with a delay in between. I want to use AceRoutine to implement a non-blocking sound manager which can use e.g. COROUTINE_DELAY in between calls to `tone()`. However, sometimes a new melody needs to be played before the previous melody is finished, in which case I want the sound manager coroutine to notice the "interruption" (not a real ISR, just the concept) and immediately switch to the new melody. I expected that I could use `Coroutine::reset` to achieve this, because it would force the coroutine to go back to the coroutine's start and start processing the new melody. However, I'm finding that calling `reset()` on the sound manager coroutine causes it to stop running somehow. After `reset()` is called the first time, the sound manager coroutine is also no longer printed from `CoroutineScheduler::list`.

Things I tried to fix it:
- After calling `reset()`, also call `setupCoroutine()` again, in the theory that maybe I needed to reinitialize the coroutine after resetting it. Weirdly, this did cause the sound manager coroutine to execute once... but never again, and also my other coroutines stopped executing too. I assume this is not the proper way to fix this.
- Remove the call to `reset()`. This did "fix" the immediate issue, however it means that the sound manager coroutine will need to manually check for the interruption condition every time it resumes from a COROUTINE_DELAY, which is a lot of ugly unnecessary work. However, this is what I'm doing now to unblock myself until I can find out whether `reset()` has a bug or I'm just not using it right.

Here is the simplest code I could get that shows the issue.

```cpp
#include <AceRoutine.h>

using namespace ace_routine;

const int SOUND_NONE = 0;
const int SOUND_BEEP = 1;

// This is the "sound manager" coroutine.
class SoundRoutine : public Coroutine {
  public:
    int runCoroutine() override;
    void playSound(int sound);
  private:
    int currentSound;
};

void SoundRoutine::playSound(int sound) {
  this->currentSound = sound;
  // Comment out this reset() call to "fix" the problem... except then I'd have to
  // implement checking-for-changed-currentSound myself.
  this->reset();
}

int SoundRoutine::runCoroutine() {
  COROUTINE_LOOP() {
    switch (this->currentSound) {
      case SOUND_NONE:
        Serial.println("<silence>");
        break;
      case SOUND_BEEP:
        // TODO: tone() will go here, interspersed with some COROUTINE_DELAYs. Ideally I do not
        // want to have to check for currentSound being changed manually after every COROUTINE_DELAY,
        // so I want to call reset() in the playSound() function to force the coroutine to return to
        // the start of the loop.
        Serial.println("First BEEP!");
        COROUTINE_DELAY(500);
        // Without reset(), I'd need to check whether currentSound is different here.
        Serial.println("Second BEEP!");
        break;
      default:
        Serial.println("Unknown sound!");
    }
    this->currentSound = SOUND_NONE;
    COROUTINE_AWAIT(this->currentSound != SOUND_NONE);
  }
}

SoundRoutine sound;

// This coroutine emulates some other piece of code that needs to be able to trigger a sound.
COROUTINE(trigger) {
  COROUTINE_LOOP() {
    COROUTINE_DELAY(5000);
    Serial.println("Triggering...");
    CoroutineScheduler::list(Serial);
    sound.playSound(SOUND_BEEP);
  }
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  sound.setupCoroutine("sound");
  CoroutineScheduler::setup();
}

void loop() {
  CoroutineScheduler::loop();
}
```

**Comment by EkardNT** [comment]
Actually, while working on implementing the workaround of not calling `reset` and instead manually checking for the interrupt condition after every delay finishes, I realized that the workaround has a serious problem. The issue is that the COROUTINE_DELAY can theoretically take an arbitrarily long time, and there's no way for outside code to force it to finish early. So if a new melody arrives, it will not actually start until the delay of the current melody finishes. This could lead to confusing lag between when a sound trigger event happens (e.g. pushing a button) and when the sound actually plays. So, I'm currently planning on just accepting that I can't achieve interruptable sounds at all until this issue is resolved.

**Comment by bxparks** [comment]
Thanks for posting that minimal validation code! You were using `reset()` correctly, you found a bug, where I was setting the internal status of the Coroutine to Suspending, instead of Yielding. I posted a fix. Also, I liked your example so much that I adopted it and added it as an example in `examples/SoundManager`.

**Comment by EkardNT** [comment]
Thank you for looking into this (and #19) so quickly! Look forward to the new version.
